### PR TITLE
use OSX sed

### PR DESCRIPTION
**Pull request by scottwn**

### CODE REVIEW

**Comment by ASzc** [comment]
I see `-E` is available in my modern Linux `sed`. I don't think it is available in older Linux `sed`s though, as the circa 2009 manpage [here](https://linux.die.net/man/1/sed) has only `-r`.

However, both my one and the 2009 one have `--regexp-extended` available, so that'd be a better option, if it's also available on OSX?

**Comment by scottwn** [comment]
I checked, `--regexp-extended` doesn't work on OSX, but maybe I can do a `sed` version check and make the option depend on the version.

**Comment by ASzc** [comment]
Could also maybe replace it with `tr -s '' '='` (squeeze mode `tr`), and avoid the problem altogether, if that'd work on OSX.

```
$ echo 'asdasdqweqwesdafsdf' | tr -s '' '='
asdasd=qweqwe=sdafsdf=
```

**Comment by ASzc** [comment]
Obsoleted by commit 6c6ffbd

**Pull request closed without merging**
